/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActivityBar: typeof import('./src/components/all/ActivityBar.vue')['default']
    Autosolve: typeof import('./src/components/blocks/autosolve.vue')['default']
    Button: typeof import('./src/components/blocks/button.vue')['default']
    Choose: typeof import('./src/components/blocks/choose.vue')['default']
    Content: typeof import('./src/components/blocks/content.vue')['default']
    Diagnostico: typeof import('./src/components/blocks/diagnostico.vue')['default']
    Group: typeof import('./src/components/blocks/group.vue')['default']
    Repeater: typeof import('./src/components/blocks/repeater.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenTransition: typeof import('./src/components/all/ScreenTransition.vue')['default']
    Slides: typeof import('./src/components/blocks/slides.vue')['default']
    Text: typeof import('./src/components/blocks/text.vue')['default']
    TimerClock: typeof import('./src/components/all/TimerClock.vue')['default']
    TimerCountdown: typeof import('./src/components/all/TimerCountdown.vue')['default']
    Variable: typeof import('./src/components/blocks/variable.vue')['default']
  }
}
