/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActivityBar: typeof import('./src/components/all/ActivityBar.vue')['default']
    Audio: typeof import('./src/components/blocks/audio.vue')['default']
    Audiorecord: typeof import('./src/components/blocks/audiorecord.vue')['default']
    Autosolve: typeof import('./src/components/blocks/autosolve.vue')['default']
    Button: typeof import('./src/components/blocks/button.vue')['default']
    Choices: typeof import('./src/components/builder/choices.vue')['default']
    Choose: typeof import('./src/components/blocks/choose.vue')['default']
    Condition: typeof import('./src/components/blocks/condition.vue')['default']
    Content: typeof import('./src/components/blocks/content.vue')['default']
    Diagnostico: typeof import('./src/components/blocks/diagnostico.vue')['default']
    Draggable: typeof import('./src/components/blocks/draggable.vue')['default']
    Finished: typeof import('./src/components/blocks/finished.vue')['default']
    Group: typeof import('./src/components/blocks/group.vue')['default']
    Icon: typeof import('./src/components/blocks/icon.vue')['default']
    Image: typeof import('./src/components/blocks/image.vue')['default']
    Imageupload: typeof import('./src/components/blocks/imageupload.vue')['default']
    LockActivityButton: typeof import('./src/components/all/LockActivityButton.vue')['default']
    Option: typeof import('./src/components/blocks/option.vue')['default']
    Record: typeof import('./src/components/blocks/record.vue')['default']
    Repeater: typeof import('./src/components/blocks/repeater.vue')['default']
    RestartButton: typeof import('./src/components/all/RestartButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneInstructions: typeof import('./src/components/all/SceneInstructions.vue')['default']
    ScreenTransition: typeof import('./src/components/all/ScreenTransition.vue')['default']
    Show: typeof import('./src/components/blocks/show.vue')['default']
    Slides: typeof import('./src/components/blocks/slides.vue')['default']
    Switch: typeof import('./src/components/blocks/switch.vue')['default']
    Symbol: typeof import('./src/components/blocks/symbol.vue')['default']
    Teacherbar: typeof import('./src/components/all/teacherbar.vue')['default']
    Teachereval: typeof import('./src/components/blocks/teachereval.vue')['default']
    Text: typeof import('./src/components/blocks/text.vue')['default']
    Textarea: typeof import('./src/components/blocks/textarea.vue')['default']
    TimerClock: typeof import('./src/components/all/TimerClock.vue')['default']
    TimerCountdown: typeof import('./src/components/all/TimerCountdown.vue')['default']
    Variable: typeof import('./src/components/blocks/variable.vue')['default']
    Video: typeof import('./src/components/blocks/video.vue')['default']
    Words: typeof import('./src/components/builder/words.vue')['default']
  }
}
